/*
 * Souffle sample file
 */

.type String
.type Int

.decl SomeRelation(foo:String, bar:String, baz:Int) input
.decl AnotherRelation() printsize
.decl YetMoreRelation(bit:String) output

// The actual rules
YetMoreRelation(thing) :-
    SomeRelation(_, thing, 2),
    SomeRelation(thing, _, 1).

YetMoreRelation(cat(right, left)), YetMoreRelation(cat(left, right)) :-
    SomeRelation(left, right, _).

